/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
/**
 *
 * @author Prateek
 */
public class Choose_Your_Restuarant extends javax.swing.JFrame {

    /**
     * Creates new form Choose_Your_Restuarant
     */
    public Choose_Your_Restuarant() {
        initComponents();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reslabel = new javax.swing.JLabel();
        byz = new javax.swing.JButton();
        bsi = new javax.swing.JButton();
        bhighway = new javax.swing.JButton();
        bmunchies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        reslabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outlet.png"))); // NOI18N
        reslabel.setText("jLabel1");
        getContentPane().add(reslabel);
        reslabel.setBounds(0, -20, 700, 720);

        byz.setMaximumSize(new java.awt.Dimension(350, 350));
        byz.setMinimumSize(new java.awt.Dimension(350, 350));
        byz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byzActionPerformed(evt);
            }
        });
        getContentPane().add(byz);
        byz.setBounds(350, 350, 350, 350);

        bsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsiActionPerformed(evt);
            }
        });
        getContentPane().add(bsi);
        bsi.setBounds(0, 350, 350, 350);

        bhighway.setMaximumSize(new java.awt.Dimension(350, 350));
        bhighway.setMinimumSize(new java.awt.Dimension(350, 350));
        bhighway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhighwayActionPerformed(evt);
            }
        });
        getContentPane().add(bhighway);
        bhighway.setBounds(350, 0, 350, 350);

        bmunchies.setMaximumSize(new java.awt.Dimension(350, 350));
        bmunchies.setMinimumSize(new java.awt.Dimension(350, 350));
        bmunchies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmunchiesActionPerformed(evt);
            }
        });
        getContentPane().add(bmunchies);
        bmunchies.setBounds(0, 0, 350, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void byzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byzActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Yz_menu().setVisible(true);
        ;
        
    }//GEN-LAST:event_byzActionPerformed

    private void bmunchiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmunchiesActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new Mun_menu().setVisible(true);
    }//GEN-LAST:event_bmunchiesActionPerformed

    private void bhighwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhighwayActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Hk_menu().setVisible(true);
    }//GEN-LAST:event_bhighwayActionPerformed

    private void bsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Si_menu().setVisible(true);
        
    }//GEN-LAST:event_bsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose_Your_Restuarant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose_Your_Restuarant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose_Your_Restuarant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose_Your_Restuarant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose_Your_Restuarant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhighway;
    private javax.swing.JButton bmunchies;
    private javax.swing.JButton bsi;
    private javax.swing.JButton byz;
    private javax.swing.JLabel reslabel;
    // End of variables declaration//GEN-END:variables
}
