
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Prateek
 */
public class Si_menu extends javax.swing.JFrame {

    static Connection con = null;
    static Statement stmt = null;
    static ResultSet rs = null;
    static PreparedStatement ps = null;
    static int amt[] = new int[40];
    static String price[] = new String[40];
    static String dishname[] = new String[40];
    static String rno;
    static String user;
    static String phno;
    static String d[] = new String[40];
    int total = 0;
    int rtc;

    /**
     * Creates new form Hk_menu
     */
    public Si_menu() {
        try {
            initComponents();
            JTableHeader header = jTable1.getTableHeader();
            header.setEnabled(false);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            connection();
            String q = "Select * from south_indian;";
            rs = stmt.executeQuery(q);
            int s = model.getRowCount();
            while (s != 0) {
                model.removeRow(0);
                s--;
            }
            while (rs.next()) {

                String name = rs.getString("Name");
                int Price = rs.getInt("Price");
                String cat = rs.getString("Category");
                Object row[] = {name, Price, cat, '0'};
                model.addRow(row);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Hk_menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void connection() {
        try {

            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project?user=root&password=");
            stmt = con.createStatement();

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error!", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menu_backg = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(700, 700));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(700, 700));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menucol.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jPanel4.add(jLabel2);
        jLabel2.setBounds(130, 130, 400, 25);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(210);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(130, 140, 400, 250);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proceed3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(600, 600, 80, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/web.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(10, 10, 80, 70);

        menu_backg.setForeground(new java.awt.Color(204, 204, 204));
        menu_backg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_16.png"))); // NOI18N
        menu_backg.setText("jLabel1");
        menu_backg.setMaximumSize(new java.awt.Dimension(700, 700));
        menu_backg.setMinimumSize(new java.awt.Dimension(700, 700));
        menu_backg.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel4.add(menu_backg);
        menu_backg.setBounds(0, 0, 700, 700);

        jTabbedPane2.addTab("Order", jPanel4);

        jPanel5.setLayout(null);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(420, 270, 100, 30);
        jPanel5.add(jTextField3);
        jTextField3.setBounds(420, 350, 100, 30);
        jPanel5.add(jTextField4);
        jTextField4.setBounds(420, 430, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(700, 700));
        jLabel3.setMinimumSize(new java.awt.Dimension(700, 700));
        jLabel3.setPreferredSize(new java.awt.Dimension(700, 700));
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);
        jPanel5.add(jLabel3);
        jLabel3.setBounds(0, -20, 700, 700);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(490, 540, 140, 70);

        jTabbedPane2.addTab("Details", jPanel5);

        jPanel1.setLayout(null);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 330, 50, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -20, 700, 700);

        jTabbedPane2.addTab("Confirmation", jPanel1);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = 0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rc = model.getRowCount();
        rtc = 0;
        //System.out.println(rc);
        while (i != rc) {
            d[i] = jTable1.getValueAt(i, 3).toString();
            if (Integer.parseInt(d[i]) != 0) {
                dishname[i] = jTable1.getValueAt(i, 0).toString();
                price[i] = jTable1.getValueAt(i, 1).toString();
                amt[i] = Integer.parseInt(price[i]) * Integer.parseInt(d[i]);
                System.out.println("\n" + d + "\n");
                rtc++;
            }
            i++;
        }

        jTabbedPane2.setSelectedIndex(1);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Welcome1().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        connection();
        user = jTextField1.getText();
        rno = jTextField3.getText();
        phno = jTextField4.getText();

        try {
            int i = 0;

            while (rtc != 0 && i < 40) {
                ps = con.prepareStatement("insert into si_admin values(?,?,?,?,?,?,?)");
                if (Integer.parseInt(d[i]) != 0) {
                    ps.setString(1, user);
                    ps.setString(2, phno);
                    ps.setString(3, rno);
                    ps.setString(4, dishname[i]);
                    ps.setString(5, price[i]);
                    ps.setString(6, d[i]);
                    ps.setInt(7, amt[i]);
                    int fu = ps.executeUpdate();
                    System.out.println(amt[i]);
                    total += amt[i];
                    rtc--;
                }
                
                i++;
            }
            jLabel5.setText(""+total);
        } catch (SQLException ex) {
            Logger.getLogger(Si_menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hk_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hk_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hk_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hk_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Si_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel menu_backg;
    // End of variables declaration//GEN-END:variables
}
